# ----------------------------------------------------
# IDENTIFICACIÓN DEL MICROSERVICIO
# ----------------------------------------------------
spring.application.name=auth-service

# ----------------------------------------------------
# CONFIGURACIÓN DEL SERVIDOR
# ----------------------------------------------------
# Puerto de este microservicio (Auth-Service)
server.port=8081

# ----------------------------------------------------
# CONFIGURACIÓN DE LA BASE DE DATOS (MSSQL)
# ----------------------------------------------------
# URL de conexión al contenedor Docker
# IMPORTANTE: Puerto 1435
spring.datasource.url=jdbc:sqlserver://localhost:1435;databaseName=DB_CorePeriodistico;trustServerCertificate=true

# Credenciales de la BD
spring.datasource.username=sa
spring.datasource.password=Ingenieri@2025LP

# Driver de SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ----------------------------------------------------
# CONFIGURACIÓN DE JPA (Hibernate)
# ----------------------------------------------------
# Hibernate en dialecto de SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.show-sql=true

# Opcional: Formatea el SQL mostrado en la consola
spring.jpa.properties.hibernate.format_sql=true

# 'validate': Comprueba que las tablas coincidan con las entidades.
spring.jpa.hibernate.ddl-auto=validate

# ----------------------------------------------------
# CONFIGURACIÓN DE SEGURIDAD DE JWT
# ----------------------------------------------------
# Clave secreta
application.security.jwt.secret-key=YjRjYThiZDQ4OWNjM2EyYmZlZGVjYjg0YjUyZTAxMzNiYWZlOGIzYjU0YjEwMTY2YzI3Y2JmZGI3NWE5NzMyYg==

# Tiempo de expiración del token
# 1000ms * 60s * 60min * 24h = 86400000
application.security.jwt.expiration=86400000